[2025-05-30T14:16:42.634+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_ecobici.procesar_datos manual__2025-05-30T14:16:21.155192+00:00 [queued]>
[2025-05-30T14:16:42.658+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_ecobici.procesar_datos manual__2025-05-30T14:16:21.155192+00:00 [queued]>
[2025-05-30T14:16:42.659+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-05-30T14:16:42.726+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): procesar_datos> on 2025-05-30 14:16:21.155192+00:00
[2025-05-30T14:16:42.731+0000] {standard_task_runner.py:60} INFO - Started process 131 to run task
[2025-05-30T14:16:42.734+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_ecobici', 'procesar_datos', 'manual__2025-05-30T14:16:21.155192+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/etl_ecobici.py', '--cfg-path', '/tmp/tmp01gumwra']
[2025-05-30T14:16:42.737+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask procesar_datos
[2025-05-30T14:16:42.865+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_ecobici.procesar_datos manual__2025-05-30T14:16:21.155192+00:00 [running]> on host ff526de6184a
[2025-05-30T14:16:43.025+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_ecobici' AIRFLOW_CTX_TASK_ID='procesar_datos' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T14:16:21.155192+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-30T14:16:21.155192+00:00'
[2025-05-30T14:16:43.026+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-30T14:16:43.028+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker exec spark spark-submit /app/dags/scripts/procesar_ecobici.py']
[2025-05-30T14:16:43.036+0000] {subprocess.py:86} INFO - Output:
[2025-05-30T14:16:47.170+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-30T14:16:47.171+0000] {subprocess.py:93} INFO -   File "/app/dags/scripts/procesar_ecobici.py", line 2, in <module>
[2025-05-30T14:16:47.174+0000] {subprocess.py:93} INFO -     from airflow.operators.docker_operator import DockerOperator
[2025-05-30T14:16:47.175+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'airflow'
[2025-05-30T14:16:47.222+0000] {subprocess.py:93} INFO - 25/05/30 14:16:47 INFO ShutdownHookManager: Shutdown hook called
[2025-05-30T14:16:47.225+0000] {subprocess.py:93} INFO - 25/05/30 14:16:47 INFO ShutdownHookManager: Deleting directory /tmp/spark-f20ed493-bd64-4a4c-b433-713e3d075717
[2025-05-30T14:16:47.269+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-30T14:16:47.288+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-30T14:16:47.292+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=etl_ecobici, task_id=procesar_datos, execution_date=20250530T141621, start_date=20250530T141642, end_date=20250530T141647
[2025-05-30T14:16:47.329+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35 for task procesar_datos (Bash command failed. The command returned a non-zero exit code 1.; 131)
[2025-05-30T14:16:47.340+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-30T14:16:47.378+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
